### ISSUE TITLE
Any help with DKMS?

### ISSUE THREAD

**Issue by a-oneil** [m-pilia/alx-wol#1]
Is there any way you could elaborate on how to make this persistent with DKMS? I've read everything that I could about this and I can't seem to make it stick. Any help would be much appreciated. Thank you!

**Comment by m-pilia** [comment]
Hi! To build a module with DKMS, you need a [dkms.conf file](https://github.com/dell/dkms/blob/master/sample.conf), placed in the folder with the sources. For this module it should be something like the following (the version number is pretty much made up): *(edit: fixed after initial comment)*
```conf
MAKE="make -C /lib/modules/\$(uname -r)/build M=\$(pwd)"
CLEAN="make -C \$(pwd) clean"
BUILT_MODULE_NAME=alx
DEST_MODULE_LOCATION=/kernel/drivers/net/ethernet/atheros/alx/
BUILT_MODULE_LOCATION="\$(pwd)"
PACKAGE_NAME=alx
PACKAGE_VERSION=0.1
AUTOINSTALL=yes
REMAKE_INITRD=yes
```

Then, you need to place the source folder in the DKMS source tree:
```bash
cp -R . /usr/src/alx-0.1
```

At this point, you can tell DKMS to register the module, build and install it:
```bash
dkms add -m alx -v 0.1
dkms build -m alx -v 0.1
dkms install -m alx -v 0.1
```

Some details may possibly need to be slightly adapted depending on your system. It is a while I do not use this, and unfortunately I do not have the hardware to test it myself anymore.

Also, I am not sure whether this version works with all recent versions of Linux or if recent changes to the kernel require to adapt the code of this module as well.

More exhaustive documentation can be found on the [DKMS manpage](http://manpages.ubuntu.com/manpages/bionic/man8/dkms.8.html), even though it may not be the easiest thing to read in order to get started.

**Comment by a-oneil** [comment]
Well this script is currently working with Parrot OS 4.19.0 on a Gigabyte Gaming 3 mobo with a "Killer Networking" NIC. I am going to try to get the DKMS to work. Thank you for the insight.

**Comment by a-oneil** [comment]
The following is the error message when attempting to run "dkms build -m alx -v 0.1"
cat /var/lib/dkms/alx/0.1/build/make.log
DKMS make.log for alx-0.1 for kernel 4.19.0-parrot1-20t-amd64 (x86_64)
Mon Mar 11 19:12:49 EDT 2019
make: Entering directory '/usr/src/linux-headers-4.19.0-parrot1-20t-amd64'
/usr/src/linux-headers-4.19.0-parrot1-20t-common/scripts/Makefile.build:45: /usr/src/linux-headers-4.19.0-parrot1-20t-common/drivers/net/ethernet/atheros/alx/Makefile: No such file or directory
make[3]: *** No rule to make target '/usr/src/linux-headers-4.19.0-parrot1-20t-common/drivers/net/ethernet/atheros/alx/Makefile'.  Stop.
make[2]: *** [/usr/src/linux-headers-4.19.0-parrot1-20t-common/Makefile:1535: _module_drivers/net/ethernet/atheros/alx] Error 2
make[1]: *** [Makefile:146: sub-make] Error 2
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/usr/src/linux-headers-4.19.0-parrot1-20t-amd64'

Currently digging into this.

**Comment by m-pilia** [comment]
Hi,
Sorry, my bad, I forgot the tree structure. Changing the following three lines in dkms.conf should work better:
```
MAKE="make -C /lib/modules/\$(uname -r)/build M=\$(pwd)"
CLEAN="make -C \$(pwd) clean"
BUILT_MODULE_LOCATION="\$(pwd)"
```
You may even [omit](http://manpages.ubuntu.com/manpages/xenial/man8/dkms.8.html#dkms.conf) `BUILT_MODULE_LOCATION`, since the resulting binary should be in the root of the sources.
